### ISSUE TITLE
Tracking next actions

### ISSUE THREAD

**Issue by arunasank** [hotosm/hot-qa-tiles#2]
## Script checklist
* [x] Set up a stack that triggers the mbtiles-update script at a certain time everyday - @arunasank
  * [x] Stack will scale up at a certain time everyday.
  * [x] Stack will scale back down after the script has finished running.
* Country extracts - @ramyaragupathy 
  * [x] Check to see if the country extracts are getting generated
  * [x] Integrate this with the rest of the script.

## Unresolved items
* **Daily updated planet.osm.pbf**: The input to the `mbtiles-update.sh` is a `planet.osm.pbf` that's generated daily. We should either use Mapbox's infrastructure that already generates this daily, or build our own. Let's get this checked with Mikel on Friday.
* **Cycling and maintaining latest tilesets**: Once we have the daily PBF issue sorted, we need to figure out maintaining the LATEST tilesets. Currently, the code for this commented out in the mbtiles-update.sh script, and we can take a call after our conversation with Mikel.

## TODO
* [ ] Write a devlog about this - @ramyaragupathy @arunasank 

cc/ @hotosm/tech-staff
